-- Query 6: List customers who haven't placed an order in the last 30 days

-- cutomers who have placed an order in the last 30 days

SELECT 
    DISTINCT C.CUSTOMERID 
FROM DIMCUSTOMER C
JOIN FACTORDERS F
ON C.CUSTOMERID = F.CUSTOMERID
JOIN DIMDATE D
ON F.DATEID = D.DATEID
WHERE D.DATE >= DATEADD(DAY, -30, CURRENT_DATE);

-- Exclude these customers using a subquery

SELECT * FROM DIMCUSTOMER 
WHERE CUSTOMERID NOT IN (
    SELECT 
    DISTINCT C.CUSTOMERID 
    FROM DIMCUSTOMER C
    JOIN FACTORDERS F
    ON C.CUSTOMERID = F.CUSTOMERID
    JOIN DIMDATE D
    ON F.DATEID = D.DATEID
    WHERE D.DATE >= DATEADD(DAY, -30, CURRENT_DATE)
);


-- Query 7: List the store that was opened most recently along with its sales
WITH STORE_RANK AS (
    SELECT 
        STOREID,
        STOREOPENINGDATE,
        ROW_NUMBER() OVER (ORDER BY STOREOPENINGDATE DESC) AS FINAL_RANK 
    FROM DIMSTORE
),
MOST_RECENT_STORE AS (
    SELECT STOREID FROM STORE_RANK WHERE FINAL_RANK = 1
),
STORE_AMOUNT AS (
    SELECT 
    O.STOREID,
    SUM(TOTALAMOUNT) AS TOTAL_SALES
    FROM FACTORDERS O
    JOIN MOST_RECENT_STORE S 
    ON O.STOREID = S.STOREID
    GROUP BY O.STOREID
)
SELECT 
    S.*, 
    A.TOTAL_SALES 
FROM DIMSTORE S
JOIN STORE_AMOUNT A
ON A.STOREID = S.STOREID;

-- Query 8: Find customers who have ordered product from more than 3 categories in the last 6 months

-- All the orders from past 6 months
SELECT 
    * 
FROM FACTORDERS F
JOIN DIMDATE D
ON F.DATEID = D.DATEID
WHERE D.DATE >= DATEADD(MONTH, -6, CURRENT_DATE);

-- selecting distinct customers with categories they ordered

SELECT 
    O.CUSTOMERID,
    COUNT(DISTINCT P.CATEGORY)
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMPRODUCT P
ON O.PRODUCTID = P.PRODUCTID
WHERE D.DATE >= DATEADD(MONTH, -6, CURRENT_DATE)
GROUP BY 
    O.CUSTOMERID
HAVING COUNT(DISTINCT P.CATEGORY) > 3;

-- Query 9: Get the monthly total sales for the current year

SELECT 
    D.MONTH,
    SUM(O.TOTALAMOUNT) AS MONTHLY_SALES_OF_CURRENT_YEAR
FROM DIMDATE D
JOIN FACTORDERS O
ON O.DATEID = D.DATEID
WHERE D.YEAR = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY MONTH
ORDER BY MONTH;

-- Query 10: Find the highest discount given on any order in the last 1 year

SELECT 
    MAX(O.DISCOUNTAMOUNT)
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
WHERE D.DATE >= DATEADD(YEAR, -1, CURRENT_DATE);

-- Query 11: Calculate the total sales by multiplying the unitPrice from product column with quantity ordered from factOrders

SELECT SUM(O.QUANTITYORDERED*P.UNITPRICE) 
FROM FACTORDERS O
JOIN DIMPRODUCT P
ON O.PRODUCTID = P.PRODUCTID;

-- Query 12: Show the customerID of the customer who has taken maximum TOTAL discount in their lifetime

SELECT CUSTOMERID FROM FACTORDERS
GROUP BY CUSTOMERID
ORDER BY SUM(DISCOUNTAMOUNT) DESC LIMIT 1;

-- Query 13: List the customer who has placed maximum number of orders till date

SELECT 
    CUSTOMERID,
    COUNT(ORDERID)
FROM FACTORDERS
GROUP BY CUSTOMERID
ORDER BY COUNT(ORDERID) DESC
LIMIT 1;

-- Query 14: Show the top 3 brands based on there sales in the last 1 year

SELECT 
    P.BRAND,
    SUM(O.TOTALAMOUNT) AS TOTAL_SALES_IN_LAST_YEAR
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMPRODUCT P
ON O.PRODUCTID = P.PRODUCTID
WHERE D.DATE >= DATEADD(YEAR, -1, CURRENT_DATE)
GROUP BY P.BRAND
ORDER BY SUM(O.TOTALAMOUNT) DESC
LIMIT 3;

-- Query 15: If the discount amount and the shipping cost was made static at 5% and 8% respectively, will the sum of new total amount be greater than the total amount we have

WITH UPDATED_TOTAL_AMOUNT AS (
    SELECT
        (ORDERAMOUNT - 0.05*ORDERAMOUNT + 0.08*ORDERAMOUNT) AS NEW_TOTAL_AMOUNT
    FROM FACTORDERS
)
SELECT 
    CASE 
        WHEN (SUM(O1.NEW_TOTAL_AMOUNT) > SUM(O.TOTALAMOUNT)) 
        THEN 'YES'
    ELSE 'NO'
    END
FROM FACTORDERS O, UPDATED_TOTAL_AMOUNT O1;

-- Query 16: Share the number of customers and their current loyalty program status

SELECT
    L.PROGRAMTIER,
    COUNT(CUSTOMERID) AS CUSTOMER_COUNT
FROM DIMCUSTOMER C
JOIN DIMLOYALTYPROGRAM L
ON C.LOYALTYPROGRAMID = L.LOYALTYPROGRAMID
GROUP BY L.PROGRAMTIER;

-- Query 17: Show the region & category wise total amount for the last 6 months

SELECT
    S.REGION,
    P.CATEGORY,
    SUM(TOTALAMOUNT) AS TOTAL_SALES
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMPRODUCT P
ON P.PRODUCTID = O.PRODUCTID
JOIN DIMSTORE S
ON O.STOREID = S.STOREID
WHERE D.DATE >= DATEADD(MONTH, -6, CURRENT_DATE)
GROUP BY 
    S.REGION,
    P.CATEGORY;

-- Query 18: Show the top 5 products based on quantity ordered in the last 3 years

SELECT 
    P.PRODUCTNAME,
    SUM(O.QUANTITYORDERED) AS QUANTITY_ORDERED
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMPRODUCT P
ON P.PRODUCTID = O.PRODUCTID
WHERE D.DATE >= DATEADD(YEAR, -3, CURRENT_DATE)
GROUP BY P.PRODUCTNAME
ORDER BY SUM(O.QUANTITYORDERED) DESC
LIMIT 5;

-- Query 19: List the total amount for each loyalty program tier since year 2023

SELECT 
    L.PROGRAMTIER,
    SUM(O.TOTALAMOUNT)
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMCUSTOMER C
ON C.CUSTOMERID = O.CUSTOMERID
JOIN DIMLOYALTYPROGRAM L
ON C.LOYALTYPROGRAMID = L.LOYALTYPROGRAMID
WHERE D.YEAR >= 2023
GROUP BY 
    L.PROGRAMTIER;

-- Query 20: Calculate the revenue generated by each store manager in June 2024

SELECT 
    S.MANAGERNAME,
    SUM(O.TOTALAMOUNT)
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMSTORE S
ON O.STOREID = S.STOREID
WHERE D.YEAR = 2024 AND D.MONTH = 6
GROUP BY S.MANAGERNAME;

-- Query 21: List the average order amount per store, along with the store name and type for the year 2024.

SELECT 
    S.STORENAME,
    S.STORETYPE,
    AVG(O.ORDERAMOUNT)
FROM FACTORDERS O
JOIN DIMDATE D
ON O.DATEID = D.DATEID
JOIN DIMSTORE S
ON O.STOREID = S.STOREID
WHERE D.YEAR = 2024
GROUP BY 
    S.STORENAME,
    S.STORETYPE;

