USE DATABASE TEST_DB;
USE SCHEMA TEST_SCHEMA;
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE USER TEST_TABLEAU_USER
    PASSWORD = 'Test_Tableau_User'
    LOGIN_NAME = 'Tableau User'
    DEFAULT_ROLE = 'ACCOUNTADMIN'
    DEFAULT_WAREHOUSE = 'COMPUTE_WH'
    MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ACCOUNTADMIN TO USER TEST_TABLEAU_USER;